import { theme, type ThemeConfig } from "antd";

const colors = {
  primary: "#3A0CA3",
  primaryHover: "#330A8F",
  primaryActive: "#2B0879",
  secondary: "#F52593",
  secondaryHover: "#DC1F84",
  secondaryActive: "#C21B74",
  success: "#1fcc00",
  darkBlue: "#7408B3",
  lightYellow: "#FFE866",
  text: "#0e1430",
  background: "#ffffff",
  surfaceSoft: "#F5EEFE",
  surfaceMuted: "#EDE0FB",
  border: "#DDC9F0",
  borderSoft: "#ECE0F7",
  outline: "rgba(58, 12, 163, 0.25)",
};

export const antdThemeConfig: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: colors.secondary,
    colorSuccess: colors.secondary,
    colorSuccessHover: colors.secondaryHover,
    colorSuccessActive: colors.secondaryActive,
    colorInfo: colors.primary,
    colorWarning: colors.lightYellow,
    colorTextBase: colors.text,
    colorBgBase: colors.background,
    colorBgContainer: colors.background,
    colorBgElevated: colors.background,
    colorFillSecondary: colors.surfaceMuted,
    colorBorder: colors.border,
    colorBorderSecondary: colors.borderSoft,
    controlItemBgHover: colors.surfaceMuted,
    controlItemBgActive: colors.surfaceSoft,
    controlOutline: colors.outline,
    controlOutlineWidth: 2,
    fontFamily: "var(--font-quicksand), sans-serif",
    borderRadius: 8,
    lineWidth: 1,
  },
  components: {
    Button: {
      colorPrimaryHover: colors.primaryHover,
      colorPrimaryActive: colors.primaryActive,
      defaultBg: colors.background,
      defaultBorderColor: colors.border,
      defaultHoverBg: colors.surfaceSoft,
      defaultHoverBorderColor: colors.primary,
      defaultHoverColor: colors.primary,
      borderRadius: 6,
    },
    Input: {
      activeBorderColor: colors.primary,
      hoverBorderColor: colors.primary,
      activeShadow: `0 0 0 2px ${colors.outline}`,
    },
    Select: {
      activeBorderColor: colors.primary,
      hoverBorderColor: colors.primary,
      optionSelectedBg: colors.surfaceSoft,
      optionActiveBg: colors.surfaceMuted,
    },
    Table: {
      headerBg: colors.surfaceMuted,
      headerColor: colors.darkBlue,
      borderColor: colors.borderSoft,
      rowHoverBg: colors.surfaceSoft,
    },
    Modal: {
      headerBg: colors.background,
      contentBg: colors.background,
      titleColor: colors.darkBlue,
    },
    Card: {
      headerBg: colors.background,
    },
    Layout: {
      headerBg: colors.surfaceMuted,
      siderBg: colors.surfaceSoft,
      bodyBg: colors.background,
    },
    Form: {
      labelFontSize: 16,
    },
    Pagination: {
      itemBg: colors.background,
      itemLinkBg: colors.background,
      itemActiveBg: colors.lightYellow,
      colorTextDisabled: "#ccc",
      colorPrimaryBorder: colors.lightYellow,
      colorPrimaryHover: colors.secondary,
      colorPrimaryText: "#ffffff",
      colorText: colors.darkBlue,
      colorTextBase: colors.darkBlue,
      colorBorder: colors.border,
      controlHeight: 30,
      itemSize: 40,
      itemSizeSM: 36,
      borderRadiusSM: 4,
    },
    Checkbox: {
      colorPrimary: colors.primary,
      colorPrimaryHover: colors.primaryHover,
      colorPrimaryActive: colors.primaryActive,
      controlInteractiveSize: 20,
      paddingContentHorizontal: 8,
    },
  },
};
