import type { Metadata } from "next";
import { ConfigProvider, App as AntdApp } from "antd";
import { Noto_Sans_JP, Lora, Quicksand } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { ReduxProvider } from "@/providers/ReduxProvider";
import { antdThemeConfig } from "@/antd-theme-config";
import "../animations/animations.css";
import "./globals.css";

const notoSans = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-lora",
  display: "swap",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-quicksand",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${lora.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ConfigProvider theme={antdThemeConfig}>
          <AntdApp component={false}>
            <ReduxProvider>
              <Toaster position="top-right" />
              {children}
            </ReduxProvider>
          </AntdApp>
        </ConfigProvider>
      </body>
    </html>
  );
}
